"""add google drive columns

Revision ID: 2b3c4d5e6f7g
Revises: 1a2b3c4d5e6f
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3c4d5e6f7g'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('drive_file_id', sa.String(), nullable=True))
    op.add_column('books', sa.Column('drive_web_link', sa.String(), nullable=True))
    op.add_column('books', sa.Column('drive_letter_folder', sa.String(), nullable=True))
    op.add_column('books', sa.Column('drive_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'drive_filename')
    op.drop_column('books', 'drive_letter_folder')
    op.drop_column('books', 'drive_web_link')
    op.drop_column('books', 'drive_file_id')
    # ### end Alembic commands ### 